# ==========================================
# Configuração de Hardware (Target)
# Placa: Open Source SDR Lab Kintex-7
# ==========================================

# Frequência do clock do sistema base em Hertz
sys_clk_freq: 100e6

# Flags globais de integração da placa
target_flags:
  # Periféricos físicos disponíveis e mapeados na placa
  - "--with-ethernet"
  - "--with-spi-sdcard"
  - "--with-video-terminal"
  
  # Configurações de rede estáticas da bancada de testes (KernelCI)
  - "--eth-ip=192.168.0.110"
  - "--remote-ip=192.168.0.193"
  
  # Configuração da porta serial para o picocom / ser2net
  - "--uart-baudrate=115200"

# Metadados de infraestrutura (ignorados pelo LiteX)
lab_bench:
  bench_id: "kintex7_vader_00"
  jtag_cable: "ft2232h"
  power_switch_port: 4