# ==========================================
# Configuração de Hardware (Target)
# Placa: Digilent Nexys4 DDR
# ==========================================

# Frequência do clock do sistema base em Hertz
sys_clk_freq: 50e6

# Flags globais de integração da placa
target_flags:
  # Periféricos físicos disponíveis e mapeados na placa
  - "--with-ethernet"
  - "--with-sdcard"
  
  # Configurações de rede estáticas da bancada de testes (KernelCI)
  - "--eth-ip=192.168.0.110"
  - "--remote-ip=192.168.0.193"
  
  # Configuração da porta serial para o picocom / ser2net
  - "--uart-baudrate=115200"

# Metadados de infraestrutura (ignorados pelo LiteX)
lab_bench:
  bench_id: "nexys4ddr_dookan_00"
  jtag_cable: "ft2232h"
  power_switch_port: 4